# Generated by Django 4.2.11 on 2024-04-09 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="work_status",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
