# Generated by Django 4.2.11 on 2024-04-09 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_customuser_work_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="work_status",
            field=models.TextField(blank=True, null=True),
        ),
    ]
