# Generated by Django 4.2.11 on 2024-04-09 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_customuser_work_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="job_type",
            field=models.CharField(
                choices=[
                    ("Looking for Work", "Looking for Work"),
                    ("Not Looking for Work", "Not Looking for Work"),
                ],
                default="Full-Time",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="work_status",
            field=models.CharField(
                choices=[
                    ("Looking for Work", "Looking for Work"),
                    ("Not Looking for Work", "Not Looking for Work"),
                ],
                default="Looking for Work",
                max_length=30,
            ),
        ),
    ]
