# Generated by Django 4.2.11 on 2024-04-09 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_customuser_job_type_alter_customuser_work_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="job_type",
            field=models.CharField(
                choices=[("Full-Time", "Full-Time"), ("Part-Time", "Part-Time")],
                default="Full-Time",
                max_length=30,
            ),
        ),
    ]
